global:
  client: xfreerdp
  connection_string: sqlite:///myrdp.sqlite
  log_level: debug

xfreerdp:
  executable: xfreerdp
  args: "+clipboard /cert-ignore +drives -themes +compression /gdi:sw +auto-reconnect -sec-nla"

rdesktop:
  executable: rdesktop
  args: "-z -r disk:test=/home -x m"
